name: Vercel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Verify Vercel Access
        run: |
          vercel whoami --token=${{ secrets.VERCEL_TOKEN }}
          vercel project ls --scope=m-husain --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --scope=m-husain --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: vercel build --prod --scope=m-husain --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: vercel deploy --prebuilt --prod --scope=m-husain --token=${{ secrets.VERCEL_TOKEN }}